# Usa la imagen oficial de Node para Angular
FROM node:latest

RUN echo 'my test'
# Establece el directorio de trabajo en el directorio de la aplicación de Angular
WORKDIR /usr/src/app

# Copia los archivos de la aplicación Angular al contenedor
COPY app/package*.json ./
RUN echo 'my package'
# Instala las dependencias de la aplicación Angular
RUN npm install
RUN echo 'my install'
# Copia el resto de los archivos de la aplicación Angular al contenedor
COPY app .
RUN echo 'my COPY'
# Expone el puerto 4200 para el servidor de desarrollo de Angular
EXPOSE 4200
RUN echo 'my 4200'
# Comando por defecto para iniciar el servidor de desarrollo de Angular
CMD ["npm", "start"]